### ISSUE TITLE
[FEA] - Add a 'stable' tag to make consistent url for use of install

### ISSUE THREAD

**Issue by scruffynerf** [damontecres/StashAppAndroidTV#10]
### Description

I added https://aftv.news/442859
but it points to v.2 only...

makes installing super simple with Downloader, but... it would be better to get one static url that Github always points to the 'latest stable' version of the apk, to have just one code to use (or to update once installed)

**Comment by damontecres** [comment]
Thanks for the feedback. I think instead, I will add the apk to each release going forward named `StashAppAndroidTV.apk`.

This means that https://github.com/damontecres/StashAppAndroidTV/releases/latest/download/StashAppAndroidTV.apk

And then created https://aftv.news/745800 for it. I'll submit a PR to update the installation instructions as well.
