### ISSUE TITLE
[FEA] - Add O-counter to EXO player controls?

### ISSUE THREAD

**Issue by argash** [damontecres/StashAppAndroidTV#102]
### Description

I'll be honest, not sure how possible this would be but could an O-counter button be added to the playback controls? If not could it be moved up next to the play button on the media details page?

**Comment by damontecres** [comment]
This makes a lot of sense. I put the OCounter button on the details page because that was easier, but it's not very intuitive.

Adding the `Create Marker` action to the player controls would be good too I think.

I think I know of a way to do this.
