### ISSUE TITLE
[FEA] - Add basic curation functions

### ISSUE THREAD

**Issue by damontecres** [damontecres/StashAppAndroidTV#3]
### Description

While the app is not intended to fully replace the WebUI nor perform any administrative functions, some basic curation functions would be nice.

- Add/Remove tags to a scene
- Add/Remove performers to a scene

Would need a good way to sort & filter the data for tagging since listings can be overwhelming.

**Comment by ChilledSlim** [comment]
I'll suggest a single button to run a _library scan_ (with the default selected options) and maybe even _Generate Content_. Likely in the options/config menu.  While you point out it shouldn't do administrative functions, if you're adding the performer to a scene, triggering those tasks is an easy way to refresh for new content.

**Comment by damontecres** [comment]
#49 adds the ability to add tags

It might be useful to also be able to remove them (like undo). This might be doable with a long click, but it's a bit more complex to add a long click listener to a leanback fragement: https://stackoverflow.com/questions/30163902/how-to-implement-a-longclicklistener-on-browsefragment-android-leanback-library

Could instead add an Undo action if changes have been made, but this would require tracking the changes which is also not simple.
