### ISSUE TITLE
Crashing back to home screen without any error message

### ISSUE THREAD

**Issue by damontecres** [damontecres/StashAppAndroidTV#338]
I'm facing a similar issue of crashing back to home screen without any error message. Been facing this issue since version 0.3 and all subsequent releases.

Device: NVIDIA Shield Pro
App Version: 0.3.2
Server version: v0.26.2
Host: Windows 11 23H2 with all latest updates
Client: Nvidia Shield TV Pro on latest update Android 11, SW Version 9.1.1

I performed a reinstall of the app after deleting the app's cache and data. I tried with both PIN and no PIN.

Steps

```
1. Open app

2. Enter PIN

3. Logs into home screen

4. Return to home screen with no error message.

5. However, if there is an app update available, the "update available" notification appears just before crashing to home screen`
```

Could the library size or something related be the issue? I am slowly migrating from Plex to stash. It might be that once I added more content that the app started crashing.
The current library size is around 26K scenes, 10K images. Around 35TB of source materials. :)

_Originally posted by @fazilps in https://github.com/damontecres/StashAppAndroidTV/issues/160#issuecomment-2254667286_

**Comment by fazilps** [comment]
Tried both the settings you mentioned - Toggling `Show position for grids` and removing network timeout. Neither worked.

The app definitely worked on an earlier version, Let me see if I can find the exact version and get a screen grab of this issue.

To reproduce:
1. Open the app and enter PIN.
2. The home page loads for a second and then crashes back to NVIDIA home page. There's no loading loop.
3. No input required. No scenes on the home page is shown, just a blank screen.

**Comment by fazilps** [comment]
[https://github.com/damontecres/StashAppAndroidTV/wiki/Tips-&-Tricks#connection-problems-with-a-large-server]

A different thing to consider:
This solution above assumes that I can get to the settings page. :)
In my situation I cannot. At least not easily.

To get to the settings page I must setup the server connection first.
Once the server connection is setup, it will crash before I can reach anywhere near the settings page.

The work around I have been using - especially to update the app itself - shut down the server first, then I can get to the settings and do what i want.

**Comment by fazilps** [comment]
Here is a video of the crash happening

https://github.com/user-attachments/assets/efb13b66-4f0e-4167-8fc1-87b216509fa8

**Comment by fazilps** [comment]
I just check an old version of the APK that I know was working - 0.2.5

That version also no longer works. Having the same issue. 

The only thing that has changed since I tried that version is the library size and the server version itself.

**Comment by fazilps** [comment]
I wish I could help you on this. Unfortunately, this is way above my knowledge level and I don't have enough time at hand to sit and learn this.

Looking forward to this app becoming a full-fledged client.

**Comment by fazilps** [comment]
Hi @damontecres 

The new function really makes it easier to get the logs. Here's mine from today. Hope it helps.
[StashppAndroidTV - Issue 338 - Error Log - 2023-08-03.txt](https://github.com/user-attachments/files/16480606/StashppAndroidTV.-.Issue.338.-.Error.Log.-.2023-08-03.txt)

**Comment by fazilps** [comment]
Issue resolved. Can confirm that it works now. Thanks a ton for working on this.
