### ISSUE TITLE
Can't add API-Key

### ISSUE THREAD

**Issue by void-naught** [damontecres/StashAppAndroidTV#468]
### Question

So i can enter the server ip/url followed by colon (:) and then port;9999 and the return key works fine in submitting the text-box input but nothing works when i am trying to submit the API-Key.
i am running the stash-android-tv-app directly from an Android phone not via firestick or any other tv-device.
i have tried using hackers-keyboard and google-keyboard/gboard. i am running this on ulefone-19-t running Android-13, i had the smart idea of looking through the "/Android/data" folder to see if i could perhaps find a file that stored the API-Key so i may be able to enter the Key directly into a configuration file, but no such luck, even though i can find the data folders of many apps via the file manager i have installed, i am not able to find "com.github.damontecres.stashapp" any where.
i think the fix would be a simple case of allowing the return/enter key to submit the form or place a submit-button on the API-Key input page.

**Comment by dscisci** [comment]
I'm having the same issue using a TV with Google TV built in. The app sideloaded fine, and I can paste the API key in using my phone as a keyboard, but there is no way to submit it and it is there where I'm stuck. As @void-naught said, a submit button would be great.
