### ISSUE TITLE
[BUG] - Fails to connect when using a URL prefix for stash

### ISSUE THREAD

**Issue by GenericMale** [damontecres/StashAppAndroidTV#58]
### Description

Can't connect to stash behind a reverse proxy with a [URL prefix](https://docs.stashapp.cc/networking/reverse-proxy/#using-a-url-prefix) (e.g. http://example.domain.com/stash).
Looks like the app always tries to connect to "/graphql", stripping the path from the configured Stash URL ([Constants.kt#L100](https://github.com/damontecres/StashAppAndroidTV/blob/631b35de034e14caa0429691a381656140e2026a/app/src/main/java/com/github/damontecres/stashapp/util/Constants.kt#L100))

### Reproduction steps

```bash
1. Setup stash behind a reverse proxy using a URL prefix according to: https://docs.stashapp.cc/networking/reverse-proxy/#using-a-url-prefix
2. Configure the Stash URL in the App including the URL prefix
```

### Device

any

**Comment by damontecres** [comment]
Good catch! #60 will fix this!
