### ISSUE TITLE
[BUG] - Video playback does not keep the device awake

### ISSUE THREAD

**Issue by bob123491234** [damontecres/StashAppAndroidTV#86]
### Description

The video player doesn't prevent the device from going to the ambient mode screensaver after a set time (10 minutes on my device). 
https://developer.android.com/develop/background-work/background-tasks/scheduling/wakelock

### Device

Onn 4K Streaming Box (2023)

**Comment by damontecres** [comment]
Hey thanks for the bug report! I put a fix together in #88.
