### ISSUE TITLE
no scrubber bar or ability to pause video 

### ISSUE THREAD

**Issue by Valgaur** [damontecres/StashAppAndroidTV#97]
### Description

when using the new exo player on firestick the scrubber does not appear when watching a video and the fast-forward, rewind and pause buttons on the remote do not work 

### Reproduction steps

```bash
1. play video 
2. try to use functions such as fast-forward, rewind and pause
3. See error
```

### Device

amazon firestick 4K

**Comment by damontecres** [comment]
Hi, thanks for the bug report. Is the video (and/or audio) playing but the on-screen controls don't appear and buttons don't respond?

Is there any error message displayed?

You can try some of the troubleshooting tips here: https://github.com/damontecres/StashAppAndroidTV/wiki/Tips-&-Tricks#general-playback-issues

**Comment by Valgaur** [comment]
yes video plays fine just no controls, no error message is shown also I have just tried the tips in the link provided but didn't seem to help

**Comment by damontecres** [comment]
Hmm... I haven't been able to reproduce this on my Fire TV Stick 4k.

One possible reason that the controls don't display is when ads are playing. I don't see how any playback from this app would be classified as an ad, but I added an override to allow showing the controls even during ad playback.

If that doesn't help, I tried to add some additional logging that might give some insight.

**Comment by damontecres** [comment]
I've managed to reproduce this on an older android version. There's nothing in the logs to explain it yet though.
